// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateStats(ctx context.Context, totalItems int32) (Stat, error)
	DeleteItem(ctx context.Context, id uuid.UUID) error
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	ListItems(ctx context.Context) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
