// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlcdb

import (
	"context"
)

const createStats = `-- name: CreateStats :one
INSERT INTO stats (total_items)
VALUES ($1)
RETURNING id, total_items, created_at
`

func (q *Queries) CreateStats(ctx context.Context, totalItems int32) (Stat, error) {
	row := q.db.QueryRow(ctx, createStats, totalItems)
	var i Stat
	err := row.Scan(&i.ID, &i.TotalItems, &i.CreatedAt)
	return i, err
}
